import { Link } from 'react-router';
import { useCatalogo } from '@/hooks/useCatalogo';
import { PageHeader, Section } from '@/components/layout/PageHeader';
import { LoadingState, ErrorState, InlineAlert } from '@/components/feedback/states';
import { Badge } from '@/components/ui/badge';
import { ROTAS } from '@/app/config/navigation';

export default function SuportePage() {
  const catalogo = useCatalogo();
  if (catalogo.isLoading) return <LoadingState label="Carregando guia de suporte..." />;
  if (catalogo.error) return <ErrorState error={catalogo.error} onRetry={() => void catalogo.refetch()} />;
  return <div className="space-y-3"><PageHeader title="Suporte e guia da aplicação" description="Como a prioridade é decidida, o significado das cores e o que cada tela faz." />
    <Section title="Como a prioridade é decidida"><ol className="list-decimal space-y-2 pl-5 text-sm"><li><strong>Camada A — regras de precedência:</strong> situações críticas configuradas, como risco iminente à vida, podem impor uma prioridade mínima independentemente dos pontos.</li><li><strong>Camada B — pontuação:</strong> cada resposta dos Casos configurados soma ou seleciona pontos conforme a regra do caso.</li><li><strong>Faixa final:</strong> o total é comparado com as faixas publicadas da cidade para definir Baixa, Média, Alta, Emergente ou Urgente.</li><li><strong>Decisão manual:</strong> um operador autorizado pode revisar a prioridade no detalhe da OS, com justificativa. O cálculo original continua registrado.</li></ol></Section>
    <Section title="Entendendo o aviso da imagem"><InlineAlert tone="danger" title="Risco iminente à vida — RISCO_VIDA / nível 3 / prioridade mínima: URG"><p>Essa linha informa que a regra de precedência <strong>RISCO_VIDA</strong> foi aplicada. Ela encontrou uma condição de risco e garante que a OS não fique abaixo de <strong>Urgente (URG)</strong>, mesmo que a soma dos pontos fosse menor. “Nível 3” é a ordem de precedência configurada para a regra; não é uma pontuação.</p></InlineAlert><p className="mt-3 text-sm text-muted">O código exibido pelo sistema é <strong>RISCO_VIDA</strong>; se houver outro texto na captura, consulte a regra cadastrada para confirmar a configuração.</p></Section>
    <Section title="Por que cada prioridade tem uma cor?"><p className="mb-3 text-sm">A cor é um sinal visual da prioridade final para leitura rápida na fila e no mapa. Ela é definida no cadastro da prioridade, não pela cor do alerta ou pela cor de uma resposta individual.</p><div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{catalogo.data?.prioridades.map((p) => <div key={p.id} className="rounded border border-line p-3"><div className="flex items-center gap-2"><span className="size-4 rounded-full" style={{ background: p.cor ?? '#64748b' }} /><strong>{p.nome}</strong><Badge variant="outline">rank {p.rank}</Badge></div><p className="mt-1 text-xs text-muted">Código {p.codigo} · triagem em {p.prazoTriagemMin} min</p></div>)}</div></Section>
    <Section title="Preciso alterar a cor?"><p className="text-sm">Normalmente, não. Mude uma cor somente se a operação aprovar uma nova convenção visual, por exemplo para acessibilidade, padronização institucional ou diferenciação operacional. Alterar a cor <strong>não muda a prioridade, os pontos, a fila nem os prazos</strong>. Para mudar a ordem de atendimento, ajuste os pontos/faixas, uma regra de precedência ou faça a revisão manual justificada da OS.</p><p className="mt-2 text-sm">A consulta atual das cores e dos prazos fica em <Link className="text-primary underline" to={ROTAS.prioridades}>Códigos e prazos</Link>.</p></Section>
    <Section title="O que cada tela faz"><div className="grid gap-3 md:grid-cols-2 text-sm"><p><strong>Dashboard:</strong> indicadores e OS no topo da fila.</p><p><strong>Nova solicitação:</strong> registra o chamado e gera a OS.</p><p><strong>Painel operacional:</strong> filtra, ordena e abre as OS.</p><p><strong>Mapa:</strong> mostra OS, equipes e subestações com coordenadas.</p><p><strong>Equipes:</strong> cadastra, consulta e atualiza a situação operacional.</p><p><strong>Formulário e pontuação:</strong> cria casos, pontos, faixas e versões.</p><p><strong>Regras de prioridade:</strong> consulta as regras da camada A.</p><p><strong>Histórico:</strong> consulta auditoria e decisões registradas.</p></div></Section>
    <Section title="Onde encontrar mais detalhes"><p className="text-sm">Os manuais completos também estão no projeto: <code>farol/MANUAL_DE_USO.md</code> e <code>farol/MANUAL_TECNICO_E_TELAS.md</code>.</p></Section>
  </div>;
}
