CREATE TABLE IF NOT EXISTS __ef_migracoes (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___ef_migracoes" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migracoes WHERE "MigrationId" = '20261010135710_Inicial') THEN
    CREATE TABLE auditoria (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        ocorrido_em timestamp with time zone NOT NULL,
        usuario_id uuid,
        usuario_nome character varying(150),
        acao character varying(40) NOT NULL,
        entidade character varying(60) NOT NULL,
        entidade_id character varying(80) NOT NULL,
        municipio_id integer,
        valores_anteriores jsonb,
        valores_novos jsonb,
        justificativa character varying(1000),
        endereco_ip character varying(64),
        CONSTRAINT pk_auditoria PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migracoes WHERE "MigrationId" = '20261010135710_Inicial') THEN
    CREATE TABLE classes_cliente (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        codigo character varying(40) NOT NULL,
        nome character varying(80) NOT NULL,
        essencial boolean NOT NULL,
        ordem integer NOT NULL,
        ativo boolean NOT NULL,
        CONSTRAINT pk_classes_cliente PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migracoes WHERE "MigrationId" = '20261010135710_Inicial') THEN
    CREATE TABLE criterios (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        codigo character varying(40) NOT NULL,
        nome character varying(120) NOT NULL,
        descricao character varying(1000),
        tipo character varying(40) NOT NULL,
        agregacao character varying(40) NOT NULL,
        multipla_escolha boolean NOT NULL,
        regra_aplicacao character varying(1000),
        ordem integer NOT NULL,
        ativo boolean NOT NULL,
        criado_por_id uuid,
        criado_em timestamp with time zone NOT NULL,
        alterado_por_id uuid,
        alterado_em timestamp with time zone NOT NULL,
        CONSTRAINT pk_criterios PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migracoes WHERE "MigrationId" = '20261010135710_Inicial') THEN
    CREATE TABLE feriados (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        data date NOT NULL,
        nome character varying(120) NOT NULL,
        municipio_id integer,
        CONSTRAINT pk_feriados PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migracoes WHERE "MigrationId" = '20261010135710_Inicial') THEN
    CREATE TABLE municipios (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        nome character varying(120) NOT NULL,
        uf character(2) NOT NULL,
        codigo_ibge character varying(7),
        prefixo character varying(6) NOT NULL,
        latitude double precision,
        longitude double precision,
        raio_km double precision,
        cep_unico character varying(8),
        ativo boolean NOT NULL,
        demonstrativo boolean NOT NULL,
        CONSTRAINT pk_municipios PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migracoes WHERE "MigrationId" = '20261010135710_Inicial') THEN
    CREATE TABLE perfis (
        id uuid NOT NULL,
        name character varying(256),
        normalized_name character varying(256),
        concurrency_stamp text,
        CONSTRAINT pk_perfis PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migracoes WHERE "MigrationId" = '20261010135710_Inicial') THEN
    CREATE TABLE prioridades (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        codigo character varying(20) NOT NULL,
        nome character varying(60) NOT NULL,
        descricao text,
        rank integer NOT NULL,
        cor character varying(7) NOT NULL,
        critica boolean NOT NULL,
        prazo_triagem_min integer NOT NULL,
        prazo_despacho_min integer NOT NULL,
        prazo_inicio_min integer NOT NULL,
        prazo_restabelecimento_min integer,
        prazo_conclusao_min integer NOT NULL,
        unidade_prazo character varying(10) NOT NULL,
        calendario character varying(40) NOT NULL,
        considera_feriados boolean NOT NULL,
        tratamento_critico text,
        escalonamento text,
        vigencia_inicio timestamp with time zone NOT NULL,
        vigencia_fim timestamp with time zone,
        ativo boolean NOT NULL,
        demonstrativa boolean NOT NULL,
        CONSTRAINT pk_prioridades PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migracoes WHERE "MigrationId" = '20261010135710_Inicial') THEN
    CREATE TABLE qualificacoes (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        codigo character varying(40) NOT NULL,
        nome text NOT NULL,
        CONSTRAINT pk_qualificacoes PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migracoes WHERE "MigrationId" = '20261010135710_Inicial') THEN
    CREATE TABLE recursos (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        codigo character varying(40) NOT NULL,
        nome text NOT NULL,
        CONSTRAINT pk_recursos PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migracoes WHERE "MigrationId" = '20261010135710_Inicial') THEN
    CREATE TABLE tipos_ocorrencia (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        codigo character varying(40) NOT NULL,
        nome character varying(120) NOT NULL,
        tipo_manutencao_sugerido character varying(40),
        ordem integer NOT NULL,
        ativo boolean NOT NULL,
        CONSTRAINT pk_tipos_ocorrencia PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migracoes WHERE "MigrationId" = '20261010135710_Inicial') THEN
    CREATE TABLE opcoes_criterio (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        criterio_id integer NOT NULL,
        codigo character varying(40) NOT NULL,
        rotulo character varying(120) NOT NULL,
        ordem integer NOT NULL,
        representa_desconhecido boolean NOT NULL,
        ativa boolean NOT NULL,
        CONSTRAINT pk_opcoes_criterio PRIMARY KEY (id),
        CONSTRAINT fk_opcoes_criterio_criterios_criterio_id FOREIGN KEY (criterio_id) REFERENCES criterios (id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migracoes WHERE "MigrationId" = '20261010135710_Inicial') THEN
    CREATE TABLE ceps (
        cep character varying(8) NOT NULL,
        logradouro text,
        bairro text,
        municipio_id integer NOT NULL,
        demonstrativo boolean NOT NULL,
        CONSTRAINT pk_ceps PRIMARY KEY (cep),
        CONSTRAINT fk_ceps_municipios_municipio_id FOREIGN KEY (municipio_id) REFERENCES municipios (id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migracoes WHERE "MigrationId" = '20261010135710_Inicial') THEN
    CREATE TABLE criterio_municipios (
        criterio_id integer NOT NULL,
        municipio_id integer NOT NULL,
        CONSTRAINT pk_criterio_municipios PRIMARY KEY (criterio_id, municipio_id),
        CONSTRAINT fk_criterio_municipios_criterios_criterio_id FOREIGN KEY (criterio_id) REFERENCES criterios (id) ON DELETE CASCADE,
        CONSTRAINT fk_criterio_municipios_municipios_municipio_id FOREIGN KEY (municipio_id) REFERENCES municipios (id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migracoes WHERE "MigrationId" = '20261010135710_Inicial') THEN
    CREATE TABLE equipes (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        codigo character varying(30) NOT NULL,
        nome character varying(120) NOT NULL,
        municipio_base_id integer NOT NULL,
        status character varying(40) NOT NULL,
        capacidade integer NOT NULL,
        latitude double precision,
        longitude double precision,
        localizacao_atualizada_em timestamp with time zone,
        origem_localizacao character varying(40),
        ativa boolean NOT NULL,
        demonstrativa boolean NOT NULL,
        CONSTRAINT pk_equipes PRIMARY KEY (id),
        CONSTRAINT fk_equipes_municipios_municipio_base_id FOREIGN KEY (municipio_base_id) REFERENCES municipios (id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migracoes WHERE "MigrationId" = '20261010135710_Inicial') THEN
    CREATE TABLE localidades (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        codigo character(3) NOT NULL,
        nome character varying(120) NOT NULL,
        municipio_id integer NOT NULL,
        demonstrativo boolean NOT NULL,
        CONSTRAINT pk_localidades PRIMARY KEY (id),
        CONSTRAINT fk_localidades_municipios_municipio_id FOREIGN KEY (municipio_id) REFERENCES municipios (id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migracoes WHERE "MigrationId" = '20261010135710_Inicial') THEN
    CREATE TABLE numeracao_sequencias (
        municipio_id integer NOT NULL,
        ano integer NOT NULL,
        tipo character varying(10) NOT NULL,
        ultimo bigint NOT NULL,
        CONSTRAINT pk_numeracao_sequencias PRIMARY KEY (municipio_id, ano, tipo),
        CONSTRAINT fk_numeracao_sequencias_municipios_municipio_id FOREIGN KEY (municipio_id) REFERENCES municipios (id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migracoes WHERE "MigrationId" = '20261010135710_Inicial') THEN
    CREATE TABLE subestacoes (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        codigo character varying(30) NOT NULL,
        nome character varying(120) NOT NULL,
        local character varying(200),
        municipio_id integer NOT NULL,
        latitude double precision,
        longitude double precision,
        demonstrativo boolean NOT NULL,
        CONSTRAINT pk_subestacoes PRIMARY KEY (id),
        CONSTRAINT fk_subestacoes_municipios_municipio_id FOREIGN KEY (municipio_id) REFERENCES municipios (id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migracoes WHERE "MigrationId" = '20261010135710_Inicial') THEN
    CREATE TABLE versoes_pontuacao (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        municipio_id integer,
        numero integer NOT NULL,
        status character varying(40) NOT NULL,
        demonstrativa boolean NOT NULL,
        vigencia_inicio timestamp with time zone,
        aplicacao character varying(40),
        justificativa character varying(1000),
        autor_id uuid,
        autor_nome text,
        criada_em timestamp with time zone NOT NULL,
        alterada_em timestamp with time zone NOT NULL,
        publicada_por_id uuid,
        publicada_por_nome text,
        publicada_em timestamp with time zone,
        aprovada_por_id uuid,
        aprovada_por_nome text,
        aprovada_em timestamp with time zone,
        reclassificacao_aplicada_em timestamp with time zone,
        restaurada_de_id integer,
        CONSTRAINT pk_versoes_pontuacao PRIMARY KEY (id),
        CONSTRAINT fk_versoes_pontuacao_municipios_municipio_id FOREIGN KEY (municipio_id) REFERENCES municipios (id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migracoes WHERE "MigrationId" = '20261010135710_Inicial') THEN
    CREATE TABLE perfil_claims (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        role_id uuid NOT NULL,
        claim_type text,
        claim_value text,
        CONSTRAINT pk_perfil_claims PRIMARY KEY (id),
        CONSTRAINT fk_perfil_claims_perfis_role_id FOREIGN KEY (role_id) REFERENCES perfis (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migracoes WHERE "MigrationId" = '20261010135710_Inicial') THEN
    CREATE TABLE regras_precedencia (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        codigo character varying(40) NOT NULL,
        nome character varying(150) NOT NULL,
        descricao character varying(1000),
        condicoes jsonb NOT NULL,
        nivel_precedencia integer NOT NULL,
        prioridade_minima_id integer NOT NULL,
        ativa boolean NOT NULL,
        demonstrativa boolean NOT NULL,
        versao integer NOT NULL,
        aprovada_por_id uuid,
        aprovada_em timestamp with time zone,
        alterada_em timestamp with time zone NOT NULL,
        CONSTRAINT pk_regras_precedencia PRIMARY KEY (id),
        CONSTRAINT fk_regras_precedencia_prioridades_prioridade_minima_id FOREIGN KEY (prioridade_minima_id) REFERENCES prioridades (id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migracoes WHERE "MigrationId" = '20261010135710_Inicial') THEN
    CREATE TABLE tipo_ocorrencia_qualificacoes (
        tipo_ocorrencia_id integer NOT NULL,
        qualificacao_id integer NOT NULL,
        CONSTRAINT pk_tipo_ocorrencia_qualificacoes PRIMARY KEY (tipo_ocorrencia_id, qualificacao_id),
        CONSTRAINT fk_tipo_ocorrencia_qualificacoes_qualificacoes_qualificacao_id FOREIGN KEY (qualificacao_id) REFERENCES qualificacoes (id) ON DELETE RESTRICT,
        CONSTRAINT "fk_tipo_ocorrencia_qualificacoes_tipos_ocorrencia_tipo_ocorren~" FOREIGN KEY (tipo_ocorrencia_id) REFERENCES tipos_ocorrencia (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migracoes WHERE "MigrationId" = '20261010135710_Inicial') THEN
    CREATE TABLE equipe_municipios (
        equipe_id integer NOT NULL,
        municipio_id integer NOT NULL,
        CONSTRAINT pk_equipe_municipios PRIMARY KEY (equipe_id, municipio_id),
        CONSTRAINT fk_equipe_municipios_equipes_equipe_id FOREIGN KEY (equipe_id) REFERENCES equipes (id) ON DELETE CASCADE,
        CONSTRAINT fk_equipe_municipios_municipios_municipio_id FOREIGN KEY (municipio_id) REFERENCES municipios (id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migracoes WHERE "MigrationId" = '20261010135710_Inicial') THEN
    CREATE TABLE equipe_qualificacoes (
        equipe_id integer NOT NULL,
        qualificacao_id integer NOT NULL,
        valida_ate date,
        CONSTRAINT pk_equipe_qualificacoes PRIMARY KEY (equipe_id, qualificacao_id),
        CONSTRAINT fk_equipe_qualificacoes_equipes_equipe_id FOREIGN KEY (equipe_id) REFERENCES equipes (id) ON DELETE CASCADE,
        CONSTRAINT fk_equipe_qualificacoes_qualificacoes_qualificacao_id FOREIGN KEY (qualificacao_id) REFERENCES qualificacoes (id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migracoes WHERE "MigrationId" = '20261010135710_Inicial') THEN
    CREATE TABLE equipe_recursos (
        equipe_id integer NOT NULL,
        recurso_id integer NOT NULL,
        CONSTRAINT pk_equipe_recursos PRIMARY KEY (equipe_id, recurso_id),
        CONSTRAINT fk_equipe_recursos_equipes_equipe_id FOREIGN KEY (equipe_id) REFERENCES equipes (id) ON DELETE CASCADE,
        CONSTRAINT fk_equipe_recursos_recursos_recurso_id FOREIGN KEY (recurso_id) REFERENCES recursos (id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migracoes WHERE "MigrationId" = '20261010135710_Inicial') THEN
    CREATE TABLE integrantes (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        equipe_id integer NOT NULL,
        nome character varying(120) NOT NULL,
        matricula character varying(30),
        funcao character varying(60),
        CONSTRAINT pk_integrantes PRIMARY KEY (id),
        CONSTRAINT fk_integrantes_equipes_equipe_id FOREIGN KEY (equipe_id) REFERENCES equipes (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migracoes WHERE "MigrationId" = '20261010135710_Inicial') THEN
    CREATE TABLE localizacoes_equipe (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        equipe_id integer NOT NULL,
        latitude double precision NOT NULL,
        longitude double precision NOT NULL,
        origem character varying(40) NOT NULL,
        registrada_em timestamp with time zone NOT NULL,
        registrada_por_id uuid,
        CONSTRAINT pk_localizacoes_equipe PRIMARY KEY (id),
        CONSTRAINT fk_localizacoes_equipe_equipes_equipe_id FOREIGN KEY (equipe_id) REFERENCES equipes (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migracoes WHERE "MigrationId" = '20261010135710_Inicial') THEN
    CREATE TABLE usuarios (
        id uuid NOT NULL,
        nome character varying(150) NOT NULL,
        ativo boolean NOT NULL,
        municipio_preferido_id integer,
        equipe_id integer,
        demonstrativo boolean NOT NULL,
        user_name character varying(256),
        normalized_user_name character varying(256),
        email character varying(256),
        normalized_email character varying(256),
        email_confirmed boolean NOT NULL,
        password_hash text,
        security_stamp text,
        concurrency_stamp text,
        phone_number text,
        phone_number_confirmed boolean NOT NULL,
        two_factor_enabled boolean NOT NULL,
        lockout_end timestamp with time zone,
        lockout_enabled boolean NOT NULL,
        access_failed_count integer NOT NULL,
        CONSTRAINT pk_usuarios PRIMARY KEY (id),
        CONSTRAINT fk_usuarios_equipes_equipe_id FOREIGN KEY (equipe_id) REFERENCES equipes (id) ON DELETE SET NULL,
        CONSTRAINT fk_usuarios_municipios_municipio_preferido_id FOREIGN KEY (municipio_preferido_id) REFERENCES municipios (id) ON DELETE SET NULL
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migracoes WHERE "MigrationId" = '20261010135710_Inicial') THEN
    CREATE TABLE conjuntos_eletricos (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        subestacao_id integer NOT NULL,
        numero character varying(30) NOT NULL,
        demonstrativo boolean NOT NULL,
        CONSTRAINT pk_conjuntos_eletricos PRIMARY KEY (id),
        CONSTRAINT fk_conjuntos_eletricos_subestacoes_subestacao_id FOREIGN KEY (subestacao_id) REFERENCES subestacoes (id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migracoes WHERE "MigrationId" = '20261010135710_Inicial') THEN
    CREATE TABLE faixas_prioridade (
        versao_pontuacao_id integer NOT NULL,
        prioridade_id integer NOT NULL,
        minimo integer NOT NULL,
        maximo integer,
        CONSTRAINT pk_faixas_prioridade PRIMARY KEY (versao_pontuacao_id, prioridade_id),
        CONSTRAINT fk_faixas_prioridade_prioridades_prioridade_id FOREIGN KEY (prioridade_id) REFERENCES prioridades (id) ON DELETE RESTRICT,
        CONSTRAINT fk_faixas_prioridade_versoes_pontuacao_versao_pontuacao_id FOREIGN KEY (versao_pontuacao_id) REFERENCES versoes_pontuacao (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migracoes WHERE "MigrationId" = '20261010135710_Inicial') THEN
    CREATE TABLE pontos_opcao (
        versao_pontuacao_id integer NOT NULL,
        opcao_id integer NOT NULL,
        pontos integer,
        requer_confirmacao boolean NOT NULL,
        origem character varying(40) NOT NULL,
        alterado_por_id uuid,
        alterado_por_nome character varying(150),
        alterado_em timestamp with time zone NOT NULL,
        CONSTRAINT pk_pontos_opcao PRIMARY KEY (versao_pontuacao_id, opcao_id),
        CONSTRAINT fk_pontos_opcao_opcoes_criterio_opcao_id FOREIGN KEY (opcao_id) REFERENCES opcoes_criterio (id) ON DELETE RESTRICT,
        CONSTRAINT fk_pontos_opcao_versoes_pontuacao_versao_pontuacao_id FOREIGN KEY (versao_pontuacao_id) REFERENCES versoes_pontuacao (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migracoes WHERE "MigrationId" = '20261010135710_Inicial') THEN
    CREATE TABLE versao_criterios (
        versao_pontuacao_id integer NOT NULL,
        criterio_id integer NOT NULL,
        habilitado boolean NOT NULL,
        CONSTRAINT pk_versao_criterios PRIMARY KEY (versao_pontuacao_id, criterio_id),
        CONSTRAINT fk_versao_criterios_criterios_criterio_id FOREIGN KEY (criterio_id) REFERENCES criterios (id) ON DELETE RESTRICT,
        CONSTRAINT fk_versao_criterios_versoes_pontuacao_versao_pontuacao_id FOREIGN KEY (versao_pontuacao_id) REFERENCES versoes_pontuacao (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migracoes WHERE "MigrationId" = '20261010135710_Inicial') THEN
    CREATE TABLE usuario_claims (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        user_id uuid NOT NULL,
        claim_type text,
        claim_value text,
        CONSTRAINT pk_usuario_claims PRIMARY KEY (id),
        CONSTRAINT fk_usuario_claims_usuarios_user_id FOREIGN KEY (user_id) REFERENCES usuarios (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migracoes WHERE "MigrationId" = '20261010135710_Inicial') THEN
    CREATE TABLE usuario_logins (
        login_provider text NOT NULL,
        provider_key text NOT NULL,
        provider_display_name text,
        user_id uuid NOT NULL,
        CONSTRAINT pk_usuario_logins PRIMARY KEY (login_provider, provider_key),
        CONSTRAINT fk_usuario_logins_usuarios_user_id FOREIGN KEY (user_id) REFERENCES usuarios (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migracoes WHERE "MigrationId" = '20261010135710_Inicial') THEN
    CREATE TABLE usuario_municipios (
        usuario_id uuid NOT NULL,
        municipio_id integer NOT NULL,
        CONSTRAINT pk_usuario_municipios PRIMARY KEY (usuario_id, municipio_id),
        CONSTRAINT fk_usuario_municipios_municipios_municipio_id FOREIGN KEY (municipio_id) REFERENCES municipios (id) ON DELETE RESTRICT,
        CONSTRAINT fk_usuario_municipios_usuarios_usuario_id FOREIGN KEY (usuario_id) REFERENCES usuarios (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migracoes WHERE "MigrationId" = '20261010135710_Inicial') THEN
    CREATE TABLE usuario_perfis (
        user_id uuid NOT NULL,
        role_id uuid NOT NULL,
        CONSTRAINT pk_usuario_perfis PRIMARY KEY (user_id, role_id),
        CONSTRAINT fk_usuario_perfis_perfis_role_id FOREIGN KEY (role_id) REFERENCES perfis (id) ON DELETE CASCADE,
        CONSTRAINT fk_usuario_perfis_usuarios_user_id FOREIGN KEY (user_id) REFERENCES usuarios (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migracoes WHERE "MigrationId" = '20261010135710_Inicial') THEN
    CREATE TABLE usuario_tokens (
        user_id uuid NOT NULL,
        login_provider text NOT NULL,
        name text NOT NULL,
        value text,
        CONSTRAINT pk_usuario_tokens PRIMARY KEY (user_id, login_provider, name),
        CONSTRAINT fk_usuario_tokens_usuarios_user_id FOREIGN KEY (user_id) REFERENCES usuarios (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migracoes WHERE "MigrationId" = '20261010135710_Inicial') THEN
    CREATE TABLE transformadores (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        numero_completo character varying(20) NOT NULL,
        codigo_localidade character(3) NOT NULL,
        numero_local character varying(17) NOT NULL,
        localidade_id integer,
        subestacao_id integer,
        conjunto_id integer,
        municipio_id integer NOT NULL,
        latitude double precision,
        longitude double precision,
        demonstrativo boolean NOT NULL,
        CONSTRAINT pk_transformadores PRIMARY KEY (id),
        CONSTRAINT fk_transformadores_conjuntos_eletricos_conjunto_id FOREIGN KEY (conjunto_id) REFERENCES conjuntos_eletricos (id) ON DELETE RESTRICT,
        CONSTRAINT fk_transformadores_localidades_localidade_id FOREIGN KEY (localidade_id) REFERENCES localidades (id) ON DELETE SET NULL,
        CONSTRAINT fk_transformadores_municipios_municipio_id FOREIGN KEY (municipio_id) REFERENCES municipios (id) ON DELETE RESTRICT,
        CONSTRAINT fk_transformadores_subestacoes_subestacao_id FOREIGN KEY (subestacao_id) REFERENCES subestacoes (id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migracoes WHERE "MigrationId" = '20261010135710_Inicial') THEN
    CREATE TABLE unidades_consumidoras (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        numero character varying(30) NOT NULL,
        cliente_nome character varying(150) NOT NULL,
        classe_cliente_id integer NOT NULL,
        situacao character varying(40) NOT NULL,
        logradouro text,
        numero_imovel text,
        bairro text,
        cep character varying(8),
        municipio_id integer NOT NULL,
        transformador_id integer,
        latitude double precision,
        longitude double precision,
        medidor text,
        fases text,
        demonstrativo boolean NOT NULL,
        CONSTRAINT pk_unidades_consumidoras PRIMARY KEY (id),
        CONSTRAINT fk_unidades_consumidoras_classes_cliente_classe_cliente_id FOREIGN KEY (classe_cliente_id) REFERENCES classes_cliente (id) ON DELETE RESTRICT,
        CONSTRAINT fk_unidades_consumidoras_municipios_municipio_id FOREIGN KEY (municipio_id) REFERENCES municipios (id) ON DELETE RESTRICT,
        CONSTRAINT fk_unidades_consumidoras_transformadores_transformador_id FOREIGN KEY (transformador_id) REFERENCES transformadores (id) ON DELETE SET NULL
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migracoes WHERE "MigrationId" = '20261010135710_Inicial') THEN
    CREATE TABLE anexos (
        id uuid NOT NULL,
        ordem_servico_id uuid NOT NULL,
        nome_arquivo character varying(255) NOT NULL,
        tipo_conteudo character varying(100) NOT NULL,
        tamanho bigint NOT NULL,
        conteudo bytea NOT NULL,
        enviado_por_id uuid NOT NULL,
        enviado_em timestamp with time zone NOT NULL,
        CONSTRAINT pk_anexos PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migracoes WHERE "MigrationId" = '20261010135710_Inicial') THEN
    CREATE TABLE comentarios (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        ordem_servico_id uuid NOT NULL,
        usuario_id uuid NOT NULL,
        usuario_nome character varying(150) NOT NULL,
        texto character varying(2000) NOT NULL,
        criado_em timestamp with time zone NOT NULL,
        CONSTRAINT pk_comentarios PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migracoes WHERE "MigrationId" = '20261010135710_Inicial') THEN
    CREATE TABLE despachos (
        id uuid NOT NULL,
        ordem_servico_id uuid NOT NULL,
        equipe_id integer NOT NULL,
        ativo boolean NOT NULL,
        designado_por_id uuid NOT NULL,
        designado_em timestamp with time zone NOT NULL,
        aceito_em timestamp with time zone,
        iniciado_em timestamp with time zone,
        encerrado_em timestamp with time zone,
        motivo_encerramento text,
        equipe_latitude double precision,
        equipe_longitude double precision,
        equipe_localizacao_em timestamp with time zone,
        distancia_km double precision,
        tempo_estimado_min double precision,
        origem_estimativa character varying(20),
        apoio_intermunicipal boolean NOT NULL,
        excecao boolean NOT NULL,
        justificativa text,
        observacao_conclusao text,
        CONSTRAINT pk_despachos PRIMARY KEY (id),
        CONSTRAINT fk_despachos_equipes_equipe_id FOREIGN KEY (equipe_id) REFERENCES equipes (id) ON DELETE RESTRICT,
        CONSTRAINT fk_despachos_usuarios_designado_por_id FOREIGN KEY (designado_por_id) REFERENCES usuarios (id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migracoes WHERE "MigrationId" = '20261010135710_Inicial') THEN
    CREATE TABLE historico_os (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        ordem_servico_id uuid NOT NULL,
        ocorrido_em timestamp with time zone NOT NULL,
        usuario_id uuid,
        usuario_nome character varying(150),
        tipo character varying(40) NOT NULL,
        descricao character varying(1000) NOT NULL,
        status_anterior text,
        status_novo text,
        justificativa character varying(1000),
        CONSTRAINT pk_historico_os PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migracoes WHERE "MigrationId" = '20261010135710_Inicial') THEN
    CREATE TABLE ordens_servico (
        id uuid NOT NULL,
        numero character varying(30) NOT NULL,
        solicitacao_id uuid NOT NULL,
        municipio_id integer NOT NULL,
        tipo_manutencao character varying(40) NOT NULL,
        tipo_ocorrencia_id integer NOT NULL,
        status character varying(40) NOT NULL,
        aberta_em timestamp with time zone NOT NULL,
        atualizada_em timestamp with time zone NOT NULL,
        encerrada_em timestamp with time zone,
        motivo_cancelamento character varying(500),
        logradouro character varying(200),
        numero_endereco character varying(200),
        bairro character varying(200),
        cep character varying(8),
        endereco_completo character varying(400),
        ponto_referencia character varying(300),
        observacoes_localizacao character varying(1000),
        latitude double precision,
        longitude double precision,
        origem_coordenada character varying(40),
        precisao_metros double precision,
        coordenada_registrada_em timestamp with time zone,
        localizacao_pendente boolean NOT NULL,
        subestacao_id integer,
        conjunto_id integer,
        transformador_numero character varying(20),
        transformador_localidade character varying(3),
        transformador_local character varying(17),
        transformador_id integer,
        origem_rede character varying(40) NOT NULL,
        trecho character varying(200),
        trecho_confirmado boolean NOT NULL,
        equipamento_descricao character varying(200),
        identificador_equipamento character varying(200),
        chave_eletrica character varying(200),
        pessoas_afetadas character varying(40) NOT NULL,
        quantidade_pessoas integer,
        ucs_afetadas character varying(40) NOT NULL,
        quantidade_ucs integer,
        servico_essencial character varying(40) NOT NULL,
        situacao_cliente character varying(40) NOT NULL,
        condicao_fornecimento character varying(40) NOT NULL,
        redundancia character varying(40) NOT NULL,
        fonte_reserva character varying(40) NOT NULL,
        equipe_especializada character varying(40) NOT NULL,
        equipamento_afetado character varying(40) NOT NULL,
        abrangencia character varying(40) NOT NULL,
        nivel_rede character varying(40) NOT NULL,
        quantidade_equipamentos integer,
        duracao_estimada_min integer,
        data_limite timestamp with time zone,
        recursos_especiais boolean NOT NULL,
        versao_pontuacao_id integer NOT NULL,
        resultado_atual_id bigint,
        prioridade_calculada_id integer,
        prioridade_id integer,
        pontuacao integer NOT NULL,
        nivel_precedencia integer NOT NULL,
        prioridade_manual_id integer,
        justificativa_manual character varying(1000),
        prazo_triagem timestamp with time zone,
        prazo_despacho timestamp with time zone,
        prazo_inicio timestamp with time zone,
        prazo_restabelecimento timestamp with time zone,
        prazo_conclusao timestamp with time zone,
        CONSTRAINT pk_ordens_servico PRIMARY KEY (id),
        CONSTRAINT fk_ordens_servico_conjuntos_eletricos_conjunto_id FOREIGN KEY (conjunto_id) REFERENCES conjuntos_eletricos (id) ON DELETE RESTRICT,
        CONSTRAINT fk_ordens_servico_municipios_municipio_id FOREIGN KEY (municipio_id) REFERENCES municipios (id) ON DELETE RESTRICT,
        CONSTRAINT fk_ordens_servico_prioridades_prioridade_calculada_id FOREIGN KEY (prioridade_calculada_id) REFERENCES prioridades (id) ON DELETE RESTRICT,
        CONSTRAINT fk_ordens_servico_prioridades_prioridade_id FOREIGN KEY (prioridade_id) REFERENCES prioridades (id) ON DELETE RESTRICT,
        CONSTRAINT fk_ordens_servico_prioridades_prioridade_manual_id FOREIGN KEY (prioridade_manual_id) REFERENCES prioridades (id) ON DELETE RESTRICT,
        CONSTRAINT fk_ordens_servico_subestacoes_subestacao_id FOREIGN KEY (subestacao_id) REFERENCES subestacoes (id) ON DELETE RESTRICT,
        CONSTRAINT fk_ordens_servico_tipos_ocorrencia_tipo_ocorrencia_id FOREIGN KEY (tipo_ocorrencia_id) REFERENCES tipos_ocorrencia (id) ON DELETE RESTRICT,
        CONSTRAINT fk_ordens_servico_transformadores_transformador_id FOREIGN KEY (transformador_id) REFERENCES transformadores (id) ON DELETE SET NULL,
        CONSTRAINT fk_ordens_servico_versoes_pontuacao_versao_pontuacao_id FOREIGN KEY (versao_pontuacao_id) REFERENCES versoes_pontuacao (id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migracoes WHERE "MigrationId" = '20261010135710_Inicial') THEN
    CREATE TABLE os_classes_cliente (
        ordem_servico_id uuid NOT NULL,
        classe_cliente_id integer NOT NULL,
        CONSTRAINT pk_os_classes_cliente PRIMARY KEY (ordem_servico_id, classe_cliente_id),
        CONSTRAINT fk_os_classes_cliente_classes_cliente_classe_cliente_id FOREIGN KEY (classe_cliente_id) REFERENCES classes_cliente (id) ON DELETE RESTRICT,
        CONSTRAINT fk_os_classes_cliente_ordens_servico_ordem_servico_id FOREIGN KEY (ordem_servico_id) REFERENCES ordens_servico (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migracoes WHERE "MigrationId" = '20261010135710_Inicial') THEN
    CREATE TABLE os_condicoes_seguranca (
        ordem_servico_id uuid NOT NULL,
        codigo character varying(40) NOT NULL,
        CONSTRAINT pk_os_condicoes_seguranca PRIMARY KEY (ordem_servico_id, codigo),
        CONSTRAINT fk_os_condicoes_seguranca_ordens_servico_ordem_servico_id FOREIGN KEY (ordem_servico_id) REFERENCES ordens_servico (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migracoes WHERE "MigrationId" = '20261010135710_Inicial') THEN
    CREATE TABLE os_recursos (
        ordem_servico_id uuid NOT NULL,
        recurso_id integer NOT NULL,
        CONSTRAINT pk_os_recursos PRIMARY KEY (ordem_servico_id, recurso_id),
        CONSTRAINT fk_os_recursos_ordens_servico_ordem_servico_id FOREIGN KEY (ordem_servico_id) REFERENCES ordens_servico (id) ON DELETE CASCADE,
        CONSTRAINT fk_os_recursos_recursos_recurso_id FOREIGN KEY (recurso_id) REFERENCES recursos (id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migracoes WHERE "MigrationId" = '20261010135710_Inicial') THEN
    CREATE TABLE os_respostas_criterio (
        ordem_servico_id uuid NOT NULL,
        criterio_id integer NOT NULL,
        opcao_id integer NOT NULL,
        CONSTRAINT pk_os_respostas_criterio PRIMARY KEY (ordem_servico_id, criterio_id, opcao_id),
        CONSTRAINT fk_os_respostas_criterio_criterios_criterio_id FOREIGN KEY (criterio_id) REFERENCES criterios (id) ON DELETE RESTRICT,
        CONSTRAINT fk_os_respostas_criterio_opcoes_criterio_opcao_id FOREIGN KEY (opcao_id) REFERENCES opcoes_criterio (id) ON DELETE RESTRICT,
        CONSTRAINT fk_os_respostas_criterio_ordens_servico_ordem_servico_id FOREIGN KEY (ordem_servico_id) REFERENCES ordens_servico (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migracoes WHERE "MigrationId" = '20261010135710_Inicial') THEN
    CREATE TABLE resultados_prioridade (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        ordem_servico_id uuid NOT NULL,
        versao_pontuacao_id integer NOT NULL,
        calculado_em timestamp with time zone NOT NULL,
        motivo character varying(40) NOT NULL,
        pontuacao integer NOT NULL,
        nivel_precedencia integer NOT NULL,
        prioridade_calculada_id integer NOT NULL,
        prioridade_id integer NOT NULL,
        regras_aplicadas jsonb NOT NULL,
        motivo_principal character varying(1000) NOT NULL,
        usuario_id uuid,
        justificativa character varying(1000),
        CONSTRAINT pk_resultados_prioridade PRIMARY KEY (id),
        CONSTRAINT fk_resultados_prioridade_ordens_servico_ordem_servico_id FOREIGN KEY (ordem_servico_id) REFERENCES ordens_servico (id) ON DELETE RESTRICT,
        CONSTRAINT fk_resultados_prioridade_prioridades_prioridade_calculada_id FOREIGN KEY (prioridade_calculada_id) REFERENCES prioridades (id) ON DELETE RESTRICT,
        CONSTRAINT fk_resultados_prioridade_prioridades_prioridade_id FOREIGN KEY (prioridade_id) REFERENCES prioridades (id) ON DELETE RESTRICT,
        CONSTRAINT fk_resultados_prioridade_versoes_pontuacao_versao_pontuacao_id FOREIGN KEY (versao_pontuacao_id) REFERENCES versoes_pontuacao (id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migracoes WHERE "MigrationId" = '20261010135710_Inicial') THEN
    CREATE TABLE solicitacoes (
        id uuid NOT NULL,
        numero character varying(40) NOT NULL,
        chave_idempotencia uuid NOT NULL,
        municipio_id integer NOT NULL,
        canal character varying(40) NOT NULL,
        origem character varying(200),
        protocolo_externo character varying(100),
        registrada_em timestamp with time zone NOT NULL,
        registrada_por_id uuid NOT NULL,
        descricao character varying(4000) NOT NULL,
        uc_nao_informada boolean NOT NULL,
        motivo_uc_nao_informada character varying(300),
        dados_informados jsonb NOT NULL,
        ordem_servico_id uuid NOT NULL,
        CONSTRAINT pk_solicitacoes PRIMARY KEY (id),
        CONSTRAINT fk_solicitacoes_municipios_municipio_id FOREIGN KEY (municipio_id) REFERENCES municipios (id) ON DELETE RESTRICT,
        CONSTRAINT fk_solicitacoes_ordens_servico_ordem_servico_id FOREIGN KEY (ordem_servico_id) REFERENCES ordens_servico (id) ON DELETE RESTRICT,
        CONSTRAINT fk_solicitacoes_usuarios_registrada_por_id FOREIGN KEY (registrada_por_id) REFERENCES usuarios (id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migracoes WHERE "MigrationId" = '20261010135710_Inicial') THEN
    CREATE TABLE resultados_prioridade_itens (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        resultado_prioridade_id bigint NOT NULL,
        criterio_codigo character varying(40) NOT NULL,
        criterio_nome character varying(120) NOT NULL,
        opcoes_codigos character varying(500) NOT NULL,
        opcoes_rotulos character varying(1000) NOT NULL,
        pontos integer NOT NULL,
        sem_pontos_definidos boolean NOT NULL,
        requer_confirmacao boolean NOT NULL,
        CONSTRAINT pk_resultados_prioridade_itens PRIMARY KEY (id),
        CONSTRAINT "fk_resultados_prioridade_itens_resultados_prioridade_resultado~" FOREIGN KEY (resultado_prioridade_id) REFERENCES resultados_prioridade (id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migracoes WHERE "MigrationId" = '20261010135710_Inicial') THEN
    CREATE TABLE solicitacao_ucs (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        solicitacao_id uuid NOT NULL,
        numero character varying(30) NOT NULL,
        unidade_consumidora_id integer,
        validada_no_cadastro boolean NOT NULL,
        CONSTRAINT pk_solicitacao_ucs PRIMARY KEY (id),
        CONSTRAINT fk_solicitacao_ucs_solicitacoes_solicitacao_id FOREIGN KEY (solicitacao_id) REFERENCES solicitacoes (id) ON DELETE CASCADE,
        CONSTRAINT fk_solicitacao_ucs_unidades_consumidoras_unidade_consumidora_id FOREIGN KEY (unidade_consumidora_id) REFERENCES unidades_consumidoras (id) ON DELETE SET NULL
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migracoes WHERE "MigrationId" = '20261010135710_Inicial') THEN
    CREATE TABLE vinculos_solicitacao (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        solicitacao_id uuid NOT NULL,
        ordem_servico_id uuid NOT NULL,
        ordem_servico_origem_id uuid,
        vinculado_por_id uuid NOT NULL,
        vinculado_em timestamp with time zone NOT NULL,
        justificativa character varying(1000) NOT NULL,
        CONSTRAINT pk_vinculos_solicitacao PRIMARY KEY (id),
        CONSTRAINT fk_vinculos_solicitacao_ordens_servico_ordem_servico_id FOREIGN KEY (ordem_servico_id) REFERENCES ordens_servico (id) ON DELETE RESTRICT,
        CONSTRAINT fk_vinculos_solicitacao_ordens_servico_ordem_servico_origem_id FOREIGN KEY (ordem_servico_origem_id) REFERENCES ordens_servico (id) ON DELETE RESTRICT,
        CONSTRAINT fk_vinculos_solicitacao_solicitacoes_solicitacao_id FOREIGN KEY (solicitacao_id) REFERENCES solicitacoes (id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migracoes WHERE "MigrationId" = '20261010135710_Inicial') THEN
    CREATE INDEX ix_anexos_ordem_servico_id ON anexos (ordem_servico_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migracoes WHERE "MigrationId" = '20261010135710_Inicial') THEN
    CREATE INDEX ix_auditoria_entidade_entidade_id ON auditoria (entidade, entidade_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migracoes WHERE "MigrationId" = '20261010135710_Inicial') THEN
    CREATE INDEX ix_auditoria_ocorrido_em ON auditoria (ocorrido_em);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migracoes WHERE "MigrationId" = '20261010135710_Inicial') THEN
    CREATE INDEX ix_ceps_municipio_id ON ceps (municipio_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migracoes WHERE "MigrationId" = '20261010135710_Inicial') THEN
    CREATE UNIQUE INDEX ix_classes_cliente_codigo ON classes_cliente (codigo);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migracoes WHERE "MigrationId" = '20261010135710_Inicial') THEN
    CREATE INDEX ix_comentarios_ordem_servico_id ON comentarios (ordem_servico_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migracoes WHERE "MigrationId" = '20261010135710_Inicial') THEN
    CREATE UNIQUE INDEX ix_conjuntos_eletricos_subestacao_id_numero ON conjuntos_eletricos (subestacao_id, numero);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migracoes WHERE "MigrationId" = '20261010135710_Inicial') THEN
    CREATE INDEX ix_criterio_municipios_municipio_id ON criterio_municipios (municipio_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migracoes WHERE "MigrationId" = '20261010135710_Inicial') THEN
    CREATE UNIQUE INDEX ix_criterios_codigo ON criterios (codigo);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migracoes WHERE "MigrationId" = '20261010135710_Inicial') THEN
    CREATE INDEX ix_despachos_designado_por_id ON despachos (designado_por_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migracoes WHERE "MigrationId" = '20261010135710_Inicial') THEN
    CREATE INDEX ix_despachos_equipe_id_ativo ON despachos (equipe_id, ativo);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migracoes WHERE "MigrationId" = '20261010135710_Inicial') THEN
    CREATE UNIQUE INDEX ux_despachos_os_ativo ON despachos (ordem_servico_id) WHERE ativo;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migracoes WHERE "MigrationId" = '20261010135710_Inicial') THEN
    CREATE INDEX ix_equipe_municipios_municipio_id ON equipe_municipios (municipio_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migracoes WHERE "MigrationId" = '20261010135710_Inicial') THEN
    CREATE INDEX ix_equipe_qualificacoes_qualificacao_id ON equipe_qualificacoes (qualificacao_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migracoes WHERE "MigrationId" = '20261010135710_Inicial') THEN
    CREATE INDEX ix_equipe_recursos_recurso_id ON equipe_recursos (recurso_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migracoes WHERE "MigrationId" = '20261010135710_Inicial') THEN
    CREATE UNIQUE INDEX ix_equipes_codigo ON equipes (codigo);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migracoes WHERE "MigrationId" = '20261010135710_Inicial') THEN
    CREATE INDEX ix_equipes_municipio_base_id ON equipes (municipio_base_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migracoes WHERE "MigrationId" = '20261010135710_Inicial') THEN
    CREATE INDEX ix_faixas_prioridade_prioridade_id ON faixas_prioridade (prioridade_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migracoes WHERE "MigrationId" = '20261010135710_Inicial') THEN
    CREATE INDEX ix_feriados_data_municipio_id ON feriados (data, municipio_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migracoes WHERE "MigrationId" = '20261010135710_Inicial') THEN
    CREATE INDEX ix_historico_os_ordem_servico_id_ocorrido_em ON historico_os (ordem_servico_id, ocorrido_em);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migracoes WHERE "MigrationId" = '20261010135710_Inicial') THEN
    CREATE INDEX ix_integrantes_equipe_id ON integrantes (equipe_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migracoes WHERE "MigrationId" = '20261010135710_Inicial') THEN
    CREATE UNIQUE INDEX ix_localidades_codigo ON localidades (codigo);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migracoes WHERE "MigrationId" = '20261010135710_Inicial') THEN
    CREATE INDEX ix_localidades_municipio_id ON localidades (municipio_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migracoes WHERE "MigrationId" = '20261010135710_Inicial') THEN
    CREATE INDEX ix_localizacoes_equipe_equipe_id_registrada_em ON localizacoes_equipe (equipe_id, registrada_em);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migracoes WHERE "MigrationId" = '20261010135710_Inicial') THEN
    CREATE UNIQUE INDEX ix_municipios_prefixo ON municipios (prefixo);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migracoes WHERE "MigrationId" = '20261010135710_Inicial') THEN
    CREATE UNIQUE INDEX ix_opcoes_criterio_criterio_id_codigo ON opcoes_criterio (criterio_id, codigo);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migracoes WHERE "MigrationId" = '20261010135710_Inicial') THEN
    CREATE INDEX ix_ordens_servico_aberta_em ON ordens_servico (aberta_em);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migracoes WHERE "MigrationId" = '20261010135710_Inicial') THEN
    CREATE INDEX ix_ordens_servico_conjunto_id ON ordens_servico (conjunto_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migracoes WHERE "MigrationId" = '20261010135710_Inicial') THEN
    CREATE INDEX ix_ordens_servico_municipio_id_status ON ordens_servico (municipio_id, status);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migracoes WHERE "MigrationId" = '20261010135710_Inicial') THEN
    CREATE UNIQUE INDEX ix_ordens_servico_numero ON ordens_servico (numero);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migracoes WHERE "MigrationId" = '20261010135710_Inicial') THEN
    CREATE INDEX ix_ordens_servico_prioridade_calculada_id ON ordens_servico (prioridade_calculada_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migracoes WHERE "MigrationId" = '20261010135710_Inicial') THEN
    CREATE INDEX ix_ordens_servico_prioridade_id ON ordens_servico (prioridade_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migracoes WHERE "MigrationId" = '20261010135710_Inicial') THEN
    CREATE INDEX ix_ordens_servico_prioridade_manual_id ON ordens_servico (prioridade_manual_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migracoes WHERE "MigrationId" = '20261010135710_Inicial') THEN
    CREATE INDEX ix_ordens_servico_resultado_atual_id ON ordens_servico (resultado_atual_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migracoes WHERE "MigrationId" = '20261010135710_Inicial') THEN
    CREATE INDEX ix_ordens_servico_solicitacao_id ON ordens_servico (solicitacao_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migracoes WHERE "MigrationId" = '20261010135710_Inicial') THEN
    CREATE INDEX ix_ordens_servico_subestacao_id ON ordens_servico (subestacao_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migracoes WHERE "MigrationId" = '20261010135710_Inicial') THEN
    CREATE INDEX ix_ordens_servico_tipo_ocorrencia_id ON ordens_servico (tipo_ocorrencia_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migracoes WHERE "MigrationId" = '20261010135710_Inicial') THEN
    CREATE INDEX ix_ordens_servico_transformador_id ON ordens_servico (transformador_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migracoes WHERE "MigrationId" = '20261010135710_Inicial') THEN
    CREATE INDEX ix_ordens_servico_transformador_numero ON ordens_servico (transformador_numero);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migracoes WHERE "MigrationId" = '20261010135710_Inicial') THEN
    CREATE INDEX ix_ordens_servico_versao_pontuacao_id ON ordens_servico (versao_pontuacao_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migracoes WHERE "MigrationId" = '20261010135710_Inicial') THEN
    CREATE INDEX ix_os_classes_cliente_classe_cliente_id ON os_classes_cliente (classe_cliente_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migracoes WHERE "MigrationId" = '20261010135710_Inicial') THEN
    CREATE INDEX ix_os_recursos_recurso_id ON os_recursos (recurso_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migracoes WHERE "MigrationId" = '20261010135710_Inicial') THEN
    CREATE INDEX ix_os_respostas_criterio_criterio_id ON os_respostas_criterio (criterio_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migracoes WHERE "MigrationId" = '20261010135710_Inicial') THEN
    CREATE INDEX ix_os_respostas_criterio_opcao_id ON os_respostas_criterio (opcao_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migracoes WHERE "MigrationId" = '20261010135710_Inicial') THEN
    CREATE INDEX ix_perfil_claims_role_id ON perfil_claims (role_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migracoes WHERE "MigrationId" = '20261010135710_Inicial') THEN
    CREATE UNIQUE INDEX role_name_index ON perfis (normalized_name);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migracoes WHERE "MigrationId" = '20261010135710_Inicial') THEN
    CREATE INDEX ix_pontos_opcao_opcao_id ON pontos_opcao (opcao_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migracoes WHERE "MigrationId" = '20261010135710_Inicial') THEN
    CREATE UNIQUE INDEX ix_prioridades_codigo ON prioridades (codigo);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migracoes WHERE "MigrationId" = '20261010135710_Inicial') THEN
    CREATE UNIQUE INDEX ix_qualificacoes_codigo ON qualificacoes (codigo);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migracoes WHERE "MigrationId" = '20261010135710_Inicial') THEN
    CREATE UNIQUE INDEX ix_recursos_codigo ON recursos (codigo);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migracoes WHERE "MigrationId" = '20261010135710_Inicial') THEN
    CREATE UNIQUE INDEX ix_regras_precedencia_codigo ON regras_precedencia (codigo);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migracoes WHERE "MigrationId" = '20261010135710_Inicial') THEN
    CREATE INDEX ix_regras_precedencia_prioridade_minima_id ON regras_precedencia (prioridade_minima_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migracoes WHERE "MigrationId" = '20261010135710_Inicial') THEN
    CREATE INDEX ix_resultados_prioridade_ordem_servico_id_calculado_em ON resultados_prioridade (ordem_servico_id, calculado_em);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migracoes WHERE "MigrationId" = '20261010135710_Inicial') THEN
    CREATE INDEX ix_resultados_prioridade_prioridade_calculada_id ON resultados_prioridade (prioridade_calculada_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migracoes WHERE "MigrationId" = '20261010135710_Inicial') THEN
    CREATE INDEX ix_resultados_prioridade_prioridade_id ON resultados_prioridade (prioridade_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migracoes WHERE "MigrationId" = '20261010135710_Inicial') THEN
    CREATE INDEX ix_resultados_prioridade_versao_pontuacao_id ON resultados_prioridade (versao_pontuacao_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migracoes WHERE "MigrationId" = '20261010135710_Inicial') THEN
    CREATE INDEX ix_resultados_prioridade_itens_resultado_prioridade_id ON resultados_prioridade_itens (resultado_prioridade_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migracoes WHERE "MigrationId" = '20261010135710_Inicial') THEN
    CREATE INDEX ix_solicitacao_ucs_numero ON solicitacao_ucs (numero);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migracoes WHERE "MigrationId" = '20261010135710_Inicial') THEN
    CREATE INDEX ix_solicitacao_ucs_solicitacao_id ON solicitacao_ucs (solicitacao_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migracoes WHERE "MigrationId" = '20261010135710_Inicial') THEN
    CREATE INDEX ix_solicitacao_ucs_unidade_consumidora_id ON solicitacao_ucs (unidade_consumidora_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migracoes WHERE "MigrationId" = '20261010135710_Inicial') THEN
    CREATE UNIQUE INDEX ix_solicitacoes_chave_idempotencia ON solicitacoes (chave_idempotencia);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migracoes WHERE "MigrationId" = '20261010135710_Inicial') THEN
    CREATE INDEX ix_solicitacoes_municipio_id_registrada_em ON solicitacoes (municipio_id, registrada_em);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migracoes WHERE "MigrationId" = '20261010135710_Inicial') THEN
    CREATE UNIQUE INDEX ix_solicitacoes_numero ON solicitacoes (numero);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migracoes WHERE "MigrationId" = '20261010135710_Inicial') THEN
    CREATE INDEX ix_solicitacoes_ordem_servico_id ON solicitacoes (ordem_servico_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migracoes WHERE "MigrationId" = '20261010135710_Inicial') THEN
    CREATE INDEX ix_solicitacoes_registrada_por_id ON solicitacoes (registrada_por_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migracoes WHERE "MigrationId" = '20261010135710_Inicial') THEN
    CREATE UNIQUE INDEX ix_subestacoes_municipio_id_codigo ON subestacoes (municipio_id, codigo);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migracoes WHERE "MigrationId" = '20261010135710_Inicial') THEN
    CREATE INDEX ix_tipo_ocorrencia_qualificacoes_qualificacao_id ON tipo_ocorrencia_qualificacoes (qualificacao_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migracoes WHERE "MigrationId" = '20261010135710_Inicial') THEN
    CREATE UNIQUE INDEX ix_tipos_ocorrencia_codigo ON tipos_ocorrencia (codigo);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migracoes WHERE "MigrationId" = '20261010135710_Inicial') THEN
    CREATE UNIQUE INDEX ix_transformadores_codigo_localidade_numero_local ON transformadores (codigo_localidade, numero_local);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migracoes WHERE "MigrationId" = '20261010135710_Inicial') THEN
    CREATE INDEX ix_transformadores_conjunto_id ON transformadores (conjunto_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migracoes WHERE "MigrationId" = '20261010135710_Inicial') THEN
    CREATE INDEX ix_transformadores_localidade_id ON transformadores (localidade_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migracoes WHERE "MigrationId" = '20261010135710_Inicial') THEN
    CREATE INDEX ix_transformadores_municipio_id ON transformadores (municipio_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migracoes WHERE "MigrationId" = '20261010135710_Inicial') THEN
    CREATE INDEX ix_transformadores_numero_completo ON transformadores (numero_completo);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migracoes WHERE "MigrationId" = '20261010135710_Inicial') THEN
    CREATE INDEX ix_transformadores_subestacao_id ON transformadores (subestacao_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migracoes WHERE "MigrationId" = '20261010135710_Inicial') THEN
    CREATE INDEX ix_unidades_consumidoras_classe_cliente_id ON unidades_consumidoras (classe_cliente_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migracoes WHERE "MigrationId" = '20261010135710_Inicial') THEN
    CREATE INDEX ix_unidades_consumidoras_municipio_id ON unidades_consumidoras (municipio_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migracoes WHERE "MigrationId" = '20261010135710_Inicial') THEN
    CREATE UNIQUE INDEX ix_unidades_consumidoras_numero ON unidades_consumidoras (numero);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migracoes WHERE "MigrationId" = '20261010135710_Inicial') THEN
    CREATE INDEX ix_unidades_consumidoras_transformador_id ON unidades_consumidoras (transformador_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migracoes WHERE "MigrationId" = '20261010135710_Inicial') THEN
    CREATE INDEX ix_usuario_claims_user_id ON usuario_claims (user_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migracoes WHERE "MigrationId" = '20261010135710_Inicial') THEN
    CREATE INDEX ix_usuario_logins_user_id ON usuario_logins (user_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migracoes WHERE "MigrationId" = '20261010135710_Inicial') THEN
    CREATE INDEX ix_usuario_municipios_municipio_id ON usuario_municipios (municipio_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migracoes WHERE "MigrationId" = '20261010135710_Inicial') THEN
    CREATE INDEX ix_usuario_perfis_role_id ON usuario_perfis (role_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migracoes WHERE "MigrationId" = '20261010135710_Inicial') THEN
    CREATE INDEX email_index ON usuarios (normalized_email);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migracoes WHERE "MigrationId" = '20261010135710_Inicial') THEN
    CREATE INDEX ix_usuarios_equipe_id ON usuarios (equipe_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migracoes WHERE "MigrationId" = '20261010135710_Inicial') THEN
    CREATE INDEX ix_usuarios_municipio_preferido_id ON usuarios (municipio_preferido_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migracoes WHERE "MigrationId" = '20261010135710_Inicial') THEN
    CREATE UNIQUE INDEX user_name_index ON usuarios (normalized_user_name);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migracoes WHERE "MigrationId" = '20261010135710_Inicial') THEN
    CREATE INDEX ix_versao_criterios_criterio_id ON versao_criterios (criterio_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migracoes WHERE "MigrationId" = '20261010135710_Inicial') THEN
    CREATE UNIQUE INDEX ix_versoes_pontuacao_municipio_id_numero ON versoes_pontuacao (municipio_id, numero) NULLS NOT DISTINCT;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migracoes WHERE "MigrationId" = '20261010135710_Inicial') THEN
    CREATE UNIQUE INDEX ux_versoes_rascunho_escopo ON versoes_pontuacao (municipio_id) NULLS NOT DISTINCT WHERE status IN ('Rascunho', 'AguardandoAprovacao');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migracoes WHERE "MigrationId" = '20261010135710_Inicial') THEN
    CREATE INDEX ix_vinculos_solicitacao_ordem_servico_id ON vinculos_solicitacao (ordem_servico_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migracoes WHERE "MigrationId" = '20261010135710_Inicial') THEN
    CREATE INDEX ix_vinculos_solicitacao_ordem_servico_origem_id ON vinculos_solicitacao (ordem_servico_origem_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migracoes WHERE "MigrationId" = '20261010135710_Inicial') THEN
    CREATE INDEX ix_vinculos_solicitacao_solicitacao_id ON vinculos_solicitacao (solicitacao_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migracoes WHERE "MigrationId" = '20261010135710_Inicial') THEN
    ALTER TABLE anexos ADD CONSTRAINT fk_anexos_ordens_servico_ordem_servico_id FOREIGN KEY (ordem_servico_id) REFERENCES ordens_servico (id) ON DELETE RESTRICT;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migracoes WHERE "MigrationId" = '20261010135710_Inicial') THEN
    ALTER TABLE comentarios ADD CONSTRAINT fk_comentarios_ordens_servico_ordem_servico_id FOREIGN KEY (ordem_servico_id) REFERENCES ordens_servico (id) ON DELETE RESTRICT;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migracoes WHERE "MigrationId" = '20261010135710_Inicial') THEN
    ALTER TABLE despachos ADD CONSTRAINT fk_despachos_ordens_servico_ordem_servico_id FOREIGN KEY (ordem_servico_id) REFERENCES ordens_servico (id) ON DELETE RESTRICT;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migracoes WHERE "MigrationId" = '20261010135710_Inicial') THEN
    ALTER TABLE historico_os ADD CONSTRAINT fk_historico_os_ordens_servico_ordem_servico_id FOREIGN KEY (ordem_servico_id) REFERENCES ordens_servico (id) ON DELETE RESTRICT;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migracoes WHERE "MigrationId" = '20261010135710_Inicial') THEN
    ALTER TABLE ordens_servico ADD CONSTRAINT fk_ordens_servico_resultados_prioridade_resultado_atual_id FOREIGN KEY (resultado_atual_id) REFERENCES resultados_prioridade (id) ON DELETE RESTRICT;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migracoes WHERE "MigrationId" = '20261010135710_Inicial') THEN
    INSERT INTO __ef_migracoes ("MigrationId", "ProductVersion")
    VALUES ('20261010135710_Inicial', '10.0.12');
    END IF;
END $EF$;
COMMIT;

